script: train.py

arguments:
  --kernel: linear
  --penalty: 1.0

compute_target: githubcluster

environment:
  pip:
    - azureml-dataprep[pandas,fuse]
    - scikit-learn
    - pandas
    - matplotlib
